/* Edu Play Lab — Universal Game Setup v1 */
(function(global){
  'use strict';
  const STORAGE_KEY='SgLDC_Universal_GameSetup_v1';
  const GROUP_IDS=['red','yellow','green','orange','purple','blue'];
  const DEFAULT_GROUP_COLORS=['#ff7f88','#ffe29a','#bfdda8','#ffc58f','#cfa7f3','#a9c8e8'];

  let ctx=null,setupConfig=null,setupDraft=null,setupValidated=false,selectedPlayerId=null;
  let setupCheckedOnce=false,setupDirty=false,setupSavedSignature=null,setupUndoStack=[],setupRedoStack=[];
  let setupHistoryApplying=false,activePointerDrag=null,suppressTouchClickUntil=0,setupToastTimer=null;
  const $=s=>document.querySelector(s);
  const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));

  function blank(){return{schema:'sgldc-game-setup',version:2,players:[],groups:GROUP_IDS.map((id,i)=>({id,name:`Group ${i+1}`,color:DEFAULT_GROUP_COLORS[i],memberIds:[]}))};}
  function normalize(raw){
    if(!raw||typeof raw!=='object')return null;
    let players=[];
    if(Array.isArray(raw.players))players=raw.players.map((p,i)=>typeof p==='string'?{id:`p${String(i+1).padStart(2,'0')}`,name:p}:{id:String(p?.id||`p${String(i+1).padStart(2,'0')}`),name:String(p?.name||'')});
    const gs=Array.isArray(raw.groups)?raw.groups:[];
    const groups=GROUP_IDS.map((id,i)=>{const g=gs[i]||{};const memberIds=Array.isArray(g.memberIds)?g.memberIds.map(String):Array.isArray(g.players)?g.players.map(name=>players.find(p=>p.name===name)?.id).filter(Boolean):[];const name=String(g.name??'').trim()||`Group ${i+1}`;return{id,name,color:/^#[0-9a-f]{6}$/i.test(String(g.color||''))?String(g.color):DEFAULT_GROUP_COLORS[i],memberIds};});
    return{schema:'sgldc-game-setup',version:2,players,groups};
  }
  function playerErrors(cfg){const names=(cfg?.players||[]).map(p=>p.name.trim()).filter(Boolean),errors=[];if(names.length!==30)errors.push(`30 player names required (${names.length} entered)`);if(names.some(n=>[...n].length>12))errors.push('Player names must be 12 characters or fewer');return errors;}
  function groupErrors(cfg){const errors=[];if((cfg?.groups||[]).some((g,i)=>[...(g.name.trim()||`Group ${i+1}`)].length>12))errors.push('Group names must be 12 characters or fewer');return errors;}
  function groupingComplete(cfg){if(!cfg)return false;const ids=new Set(cfg.players.map(p=>p.id)),assigned=cfg.groups.flatMap(g=>g.memberIds);return cfg.groups.length===6&&cfg.groups.every(g=>g.memberIds.length===5)&&assigned.length===30&&new Set(assigned).size===30&&assigned.every(id=>ids.has(id));}
  function isReady(cfg){return !!cfg&&playerErrors(cfg).length===0&&groupErrors(cfg).length===0&&groupingComplete(cfg);}
  function rosterReady(cfg=setupDraft){if(!cfg)return false;const names=cfg.players.map(p=>p.name.trim()).filter(Boolean);return names.length===30&&!names.some(n=>[...n].length>12)&&groupErrors(cfg).length===0;}
  function toGroups(cfg){const n=normalize(cfg);const out={};if(!n)return out;GROUP_IDS.forEach((id,i)=>{const g=n.groups[i];out[id]={name:g.name.trim()||`Group ${i+1}`,color:g.color,players:g.memberIds.map(pid=>n.players.find(p=>p.id===pid)?.name).filter(Boolean)};});return out;}
  function load(){try{const cfg=normalize(JSON.parse(localStorage.getItem(STORAGE_KEY)||'null'));return isReady(cfg)?cfg:null;}catch(e){return null;}}
  function persist(cfg){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(normalize(cfg)));}catch(e){}}
  function signature(cfg){const n=normalize(cfg);if(!n)return '';return JSON.stringify({players:n.players.map(p=>({id:p.id,name:p.name})),groups:n.groups.map(g=>({name:g.name,color:g.color,memberIds:[...g.memberIds]}))});}
  function clone(cfg){return cfg?normalize(JSON.parse(JSON.stringify(cfg))):null;}
  function errorSound(){try{ctx?.errorSound?.();}catch(e){}}
  function successSound(){try{ctx?.successSound?.();}catch(e){}}

  function recomputeValidation(){setupValidated=rosterReady(setupDraft);setupCheckedOnce=setupValidated;}
  function refreshButtons(){const r=$('#randomizeBtn'),a=$('#addToGameBtn'),d=$('#downloadSetupBtn'),ok=rosterReady(setupDraft);if(r)r.disabled=!ok;if(d)d.disabled=!ok;if(a)a.disabled=!!setupSavedSignature&&!setupDirty;}
  function markDirty(){setupDirty=true;recomputeValidation();refreshButtons();}
  function currentDraftFromUI(){if(!setupDraft)return blank();setupDraft.groups.forEach((g,i)=>{g.name=($(`#groupName-${i}`)?.value||g.name).trim()||`Group ${i+1}`;g.color=$(`#groupColor-${i}`)?.value||g.color;});return setupDraft;}
  function historyEntry(){if(!setupDraft)return null;let cfg;try{cfg=currentDraftFromUI();}catch(e){cfg=setupDraft;}return{cfg:clone(cfg),validated:!!setupValidated,checked:!!setupCheckedOnce};}
  function refreshHistory(){const u=$('#undoSetupBtn'),r=$('#redoSetupBtn');if(u)u.disabled=!setupUndoStack.length;if(r)r.disabled=!setupRedoStack.length;}
  function recordHistory(){if(setupHistoryApplying)return;const entry=historyEntry();if(!entry?.cfg)return;const sig=signature(entry.cfg)+'|'+entry.validated+'|'+entry.checked,last=setupUndoStack[setupUndoStack.length-1],lastSig=last?signature(last.cfg)+'|'+last.validated+'|'+last.checked:'';if(sig!==lastSig)setupUndoStack.push(entry);if(setupUndoStack.length>60)setupUndoStack.shift();setupRedoStack=[];refreshHistory();}
  function applyHistory(entry,label){if(!entry?.cfg)return;setupHistoryApplying=true;setupDraft=clone(entry.cfg);selectedPlayerId=null;setupDraft.groups.forEach((g,i)=>{const n=$(`#groupName-${i}`),c=$(`#groupColor-${i}`);if(n)n.value=g.name;if(c)c.value=g.color;});recomputeValidation();setupDirty=setupSavedSignature!==signature(setupDraft);setupHistoryApplying=false;renderTags();refreshButtons();refreshHistory();toast(`<strong>${label}.</strong> Review the setup, then add the player names to the game if needed.`,'good');}
  function undo(){if(!setupUndoStack.length)return;const cur=historyEntry();if(cur)setupRedoStack.push(cur);applyHistory(setupUndoStack.pop(),'Undo complete');}
  function redo(){if(!setupRedoStack.length)return;const cur=historyEntry();if(cur)setupUndoStack.push(cur);applyHistory(setupRedoStack.pop(),'Redo complete');}
  function armTextHistory(el){if(!el)return;let captured=false;el.addEventListener('focus',()=>captured=false);el.addEventListener('beforeinput',()=>{if(!captured){recordHistory();captured=true;}});el.addEventListener('blur',()=>captured=false);}

  function clearPointer(){document.querySelectorAll('.group-card.drag-over,.player-bank.drag-over').forEach(el=>el.classList.remove('drag-over'));if(activePointerDrag?.ghost)activePointerDrag.ghost.remove();activePointerDrag=null;}
  function pointerTarget(x,y){const el=document.elementFromPoint(x,y);if(!el)return null;const drop=el.closest?.('.group-drop');if(drop)return{type:'group',index:Number(drop.dataset.groupIndex)};const bank=el.closest?.('.player-bank');if(bank)return{type:'bank'};return null;}
  function positionGhost(x,y){if(activePointerDrag?.ghost){activePointerDrag.ghost.style.left=x+'px';activePointerDrag.ghost.style.top=y+'px';}}
  function beginPointer(e,tag,player){if(!setupDraft||e.pointerType==='mouse'||activePointerDrag)return;e.preventDefault();selectedPlayerId=null;document.querySelectorAll('.player-tag').forEach(t=>t.classList.remove('selected'));const ghost=tag.cloneNode(true);ghost.classList.add('touch-drag-ghost');ghost.classList.remove('selected');const r=tag.getBoundingClientRect();ghost.style.width=r.width+'px';document.body.appendChild(ghost);activePointerDrag={pointerId:e.pointerId,playerId:player.id,ghost,startX:e.clientX,startY:e.clientY,dragged:false};positionGhost(e.clientX,e.clientY);try{tag.setPointerCapture(e.pointerId);}catch(err){}}
  function movePointer(e){if(!activePointerDrag||activePointerDrag.pointerId!==e.pointerId)return;e.preventDefault();if(Math.hypot(e.clientX-activePointerDrag.startX,e.clientY-activePointerDrag.startY)>7)activePointerDrag.dragged=true;positionGhost(e.clientX,e.clientY);document.querySelectorAll('.group-card.drag-over,.player-bank.drag-over').forEach(el=>el.classList.remove('drag-over'));const target=pointerTarget(e.clientX,e.clientY);if(target?.type==='group')$(`#groupCard-${target.index}`)?.classList.add('drag-over');else if(target?.type==='bank')$('#playerTags')?.closest('.player-bank')?.classList.add('drag-over');}
  function endPointer(e,player){if(!activePointerDrag||activePointerDrag.pointerId!==e.pointerId)return;e.preventDefault();const drag=activePointerDrag,target=pointerTarget(e.clientX,e.clientY),wasDragged=drag.dragged;clearPointer();suppressTouchClickUntil=Date.now()+450;if(wasDragged&&target?.type==='group')moveToGroup(drag.playerId,target.index);else if(wasDragged&&target?.type==='bank')moveToBank(drag.playerId);else if(!wasDragged)toggleSelection(player);}
  function toggleSelection(player){if(selectedPlayerId===player.id){selectedPlayerId=null;document.querySelectorAll('.player-tag').forEach(t=>t.classList.remove('selected'));return;}selectedPlayerId=player.id;document.querySelectorAll('.player-tag').forEach(t=>t.classList.toggle('selected',t.dataset.playerId===player.id));}

  function toast(message,type=''){if(!type)return;const el=$('#setupToast');if(!el||!message)return;if(setupToastTimer)clearTimeout(setupToastTimer);el.className=`setup-toast ${type}`;el.innerHTML=message;requestAnimationFrame(()=>el.classList.add('show'));setupToastTimer=setTimeout(()=>{el.classList.remove('show');setupToastTimer=null;},type==='bad'?4200:2800);}
  function splitNames(text){return String(text||'').split(/\r?\n|\t/).map(x=>x.trim()).filter(Boolean);}
  function bindNameEntry(el,onCommit){if(!el)return;const commit=()=>{const names=splitNames(el.value);el.value='';if(names.length)onCommit(names);};el.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();commit();}});el.addEventListener('input',()=>{if(/[\r\n]/.test(el.value)){const parts=el.value.split(/\r?\n/),tail=parts.pop()||'';el.value=tail;const names=parts.map(x=>x.trim()).filter(Boolean);if(names.length)onCommit(names);}});el.addEventListener('paste',e=>{const text=e.clipboardData?.getData('text')||'';if(/[\r\n\t]/.test(text)){e.preventDefault();el.value='';const names=splitNames(text);if(names.length)onCommit(names);}});el.addEventListener('blur',()=>{if(el.value.trim())commit();});}
  function nextPlayerId(){const ids=new Set((setupDraft?.players||[]).map(p=>p.id));let n=1,id='';do{id=`p${String(n++).padStart(2,'0')}`;}while(ids.has(id));return id;}
  function addToBank(names){if(!setupDraft||!names.length)return;const clean=names.map(n=>String(n).trim()).filter(Boolean),tooLong=clean.filter(n=>[...n].length>12);if(tooLong.length){toast(`<strong>Player name too long:</strong> ${esc(tooLong[0])}. Use 12 characters or fewer.`,'bad');errorSound();return;}const space=Math.max(0,30-setupDraft.players.length);if(!space){toast('<strong>30/30 player names entered.</strong> The roster is full.','bad');errorSound();return;}recordHistory();const accepted=clean.slice(0,space);accepted.forEach(name=>setupDraft.players.push({id:nextPlayerId(),name}));markDirty();renderTags();if(clean.length>accepted.length)toast(`<strong>30-player limit reached.</strong> ${clean.length-accepted.length} extra name${clean.length-accepted.length===1?' was':'s were'} not added.`,'bad');}
  function addToGroup(names,index){if(!setupDraft||!names.length)return;const target=setupDraft.groups[index];if(!target)return;const clean=names.map(n=>String(n).trim()).filter(Boolean),tooLong=clean.filter(n=>[...n].length>12);if(tooLong.length){toast(`<strong>Player name too long:</strong> ${esc(tooLong[0])}. Use 12 characters or fewer.`,'bad');errorSound();return;}let slots=Math.max(0,5-target.memberIds.length);if(!slots){toast(`<strong>${esc(target.name||`Group ${index+1}`)}</strong> already has 5 players.`,'bad');errorSound();return;}recordHistory();let added=0,skipped=0;for(const name of clean){if(slots<=0){skipped++;continue;}const assigned=new Set(setupDraft.groups.flatMap(g=>g.memberIds));let player=setupDraft.players.find(p=>p.name===name&&!assigned.has(p.id));if(!player){if(setupDraft.players.length>=30){skipped++;continue;}player={id:nextPlayerId(),name};setupDraft.players.push(player);}target.memberIds.push(player.id);slots--;added++;}if(added){selectedPlayerId=null;markDirty();renderTags();}if(skipped){toast('<strong>Some names were not added.</strong> A group can hold 5 players and the full roster can hold 30.','bad');errorSound();}}
  function makeTag(player,groupIndex){const tag=document.createElement('div');tag.className='player-tag'+(groupIndex!==null?' assigned':'');tag.draggable=true;tag.dataset.playerId=player.id;tag.textContent=player.name;if(groupIndex!==null)tag.style.background=setupDraft.groups[groupIndex].color;tag.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/plain',player.id);e.dataTransfer.effectAllowed='move';selectedPlayerId=player.id;});tag.addEventListener('pointerdown',e=>beginPointer(e,tag,player));tag.addEventListener('pointermove',movePointer);tag.addEventListener('pointerup',e=>endPointer(e,player));tag.addEventListener('pointercancel',clearPointer);tag.addEventListener('click',e=>{if(Date.now()<suppressTouchClickUntil){e.preventDefault();return;}toggleSelection(player);});return tag;}
  function bindDrop(drop,index){drop.ondragover=e=>{e.preventDefault();drop.closest('.group-card').classList.add('drag-over');};drop.ondragleave=()=>drop.closest('.group-card').classList.remove('drag-over');drop.ondrop=e=>{e.preventDefault();drop.closest('.group-card').classList.remove('drag-over');moveToGroup(e.dataTransfer.getData('text/plain'),index);};drop.onclick=e=>{if(e.target.closest('.player-tag,.group-entry'))return;if(selectedPlayerId)moveToGroup(selectedPlayerId,index);};}
  function moveToGroup(playerId,index){if(!setupDraft)return;const target=setupDraft.groups[index],current=setupDraft.groups.findIndex(g=>g.memberIds.includes(playerId));if(current===index)return;if(target.memberIds.length>=5){toast(`<strong>${esc(target.name||`Group ${index+1}`)}</strong> already has 5 players.`,'bad');errorSound();return;}recordHistory();if(current>=0)setupDraft.groups[current].memberIds=setupDraft.groups[current].memberIds.filter(id=>id!==playerId);target.memberIds.push(playerId);selectedPlayerId=null;markDirty();renderTags();const assigned=setupDraft.groups.reduce((n,g)=>n+g.memberIds.length,0);if(assigned===30)toast('<strong>30/30 players assigned a group.</strong> Ready to add the player names to the game.','good');}
  function moveToBank(playerId){if(!setupDraft)return;const current=setupDraft.groups.findIndex(g=>g.memberIds.includes(playerId));if(current<0)return;recordHistory();setupDraft.groups[current].memberIds=setupDraft.groups[current].memberIds.filter(id=>id!==playerId);selectedPlayerId=null;markDirty();renderTags();}
  function randomize(){if(!rosterReady(setupDraft)){toast('<strong>Randomize needs exactly 30 valid player names.</strong>','bad');errorSound();return;}recordHistory();const ids=[...setupDraft.players.map(p=>p.id)];for(let i=ids.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[ids[i],ids[j]]=[ids[j],ids[i]];}setupDraft.groups.forEach((g,i)=>g.memberIds=ids.slice(i*5,i*5+5));selectedPlayerId=null;markDirty();renderTags();toast('<strong>Randomized.</strong> All 30 players have been assigned a group.','good');}
  function renderTags(){if(!setupDraft)return;const assignedMap=new Map();setupDraft.groups.forEach((g,gi)=>g.memberIds.forEach(pid=>assignedMap.set(pid,gi)));const bank=$('#playerTags');if(!bank)return;bank.innerHTML='';setupDraft.players.forEach(p=>{if(!assignedMap.has(p.id))bank.appendChild(makeTag(p,null));});const panel=bank.closest('.player-bank');panel.ondragover=e=>e.preventDefault();panel.ondrop=e=>{e.preventDefault();moveToBank(e.dataTransfer.getData('text/plain'));};bank.onclick=e=>{if(e.target.closest('.player-tag'))return;if(selectedPlayerId)moveToBank(selectedPlayerId);};$('#playerCount').textContent=`${setupDraft.players.length}/30`;setupDraft.groups.forEach((g,i)=>{const drop=$(`#groupDrop-${i}`),count=$(`#groupCount-${i}`);drop.innerHTML='';g.memberIds.forEach(pid=>{const p=setupDraft.players.find(x=>x.id===pid);if(p)drop.appendChild(makeTag(p,i));});if(g.memberIds.length<5){const entry=document.createElement('textarea');entry.className='group-entry';entry.rows=1;entry.spellcheck=false;entry.placeholder='Type, paste or drag names';entry.setAttribute('aria-label',`Add player names to ${g.name||`Group ${i+1}`}`);bindNameEntry(entry,names=>addToGroup(names,i));drop.appendChild(entry);}if(count)count.textContent=`${g.memberIds.length}/5 players`;const card=$(`#groupCard-${i}`);card.classList.toggle('full',g.memberIds.length===5);bindDrop(drop,i);});recomputeValidation();refreshButtons();}

  function addToGame(){const bank=$('#playerNamesInput');if(bank?.value.trim()){const names=splitNames(bank.value);bank.value='';if(names.length)addToBank(names);}setupDraft=currentDraftFromUI();const errors=[...playerErrors(setupDraft),...groupErrors(setupDraft)];if(errors.length){toast(`<strong>Cannot add to game:</strong> ${errors.join(' · ')}`,'bad');errorSound();return;}const assigned=setupDraft.groups.reduce((n,g)=>n+g.memberIds.length,0);if(!groupingComplete(setupDraft)){refreshButtons();toast(`<strong>Cannot add to game:</strong> ${assigned}/30 players assigned a group. Assign to groups first.`,'bad');errorSound();return;}persist(setupDraft);setupConfig=normalize(setupDraft);setupSavedSignature=signature(setupConfig);setupDirty=false;try{if(ctx?.gameStateKey)localStorage.removeItem(ctx.gameStateKey);}catch(e){}try{ctx?.onApply?.(clone(setupConfig));}catch(e){}refreshButtons();successSound();toast('<strong>Player names added to game.</strong> You can Download this setup or make further changes.','good');}
  function cleanField(value){return String(value??'').replace(/[\t\r\n]+/g,' ').trim();}
  function serialize(cfg){const n=normalize(cfg),lines=['SGLDC_GAME_SETUP\t2','# Portable classroom game setup','# PLAYER = player id + name','# GROUP = group id + group name + colour','# ASSIGN = player id + group id'];n.players.forEach(p=>lines.push(`PLAYER\t${cleanField(p.id)}\t${cleanField(p.name)}`));n.groups.forEach((g,i)=>lines.push(`GROUP\t${GROUP_IDS[i]}\t${cleanField(g.name)}\t${cleanField(g.color)}`));n.groups.forEach((g,i)=>g.memberIds.forEach(pid=>lines.push(`ASSIGN\t${cleanField(pid)}\t${GROUP_IDS[i]}`)));return lines.join('\n')+'\n';}
  function parseText(text){const lines=String(text||'').split(/\r?\n/).map(line=>line.trim()).filter(line=>line&&!line.startsWith('#'));if(!lines.length||!/^SGLDC_GAME_SETUP(?:\t|\s)+2$/i.test(lines[0]))return null;const players=[],groupMap=new Map(),assignments=[];for(const line of lines.slice(1)){const parts=line.split('\t'),type=(parts.shift()||'').toUpperCase();if(type==='PLAYER'&&parts.length>=2){const id=parts.shift().trim(),name=parts.join('\t').trim();if(id)players.push({id,name});}else if(type==='GROUP'&&parts.length>=3){const id=parts.shift().trim(),name=parts.shift().trim(),color=parts.shift().trim();groupMap.set(id,{id,name,color,memberIds:[]});}else if(type==='ASSIGN'&&parts.length>=2)assignments.push({playerId:parts[0].trim(),groupId:parts[1].trim()});}if(!players.length)return null;const groups=GROUP_IDS.map((id,i)=>{const g=groupMap.get(id)||{id,name:'',color:DEFAULT_GROUP_COLORS[i]};return{id,name:g.name,color:g.color,memberIds:[]};});assignments.forEach(a=>{const gi=GROUP_IDS.indexOf(a.groupId);if(gi>=0&&players.some(p=>p.id===a.playerId)&&!groups[gi].memberIds.includes(a.playerId))groups[gi].memberIds.push(a.playerId);});return normalize({schema:'sgldc-game-setup',version:2,players,groups});}
  function parseCompatible(text){const portable=parseText(text);if(portable)return portable;try{return normalize(JSON.parse(text));}catch(e){}const start=text.indexOf('{'),end=text.lastIndexOf('}');if(start>=0&&end>start){try{return normalize(JSON.parse(text.slice(start,end+1)));}catch(e){}}return null;}
  function download(){const bank=$('#playerNamesInput');if(bank?.value.trim()){const names=splitNames(bank.value);bank.value='';if(names.length)addToBank(names);}const cfg=currentDraftFromUI(),errors=[...playerErrors(cfg),...groupErrors(cfg)];if(errors.length){toast(`<strong>Cannot download:</strong> ${errors.join(' · ')}`,'bad');errorSound();return;}const blob=new Blob([serialize(cfg)],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Game_Setup.txt';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),0);toast('<strong>Game_Setup.txt downloaded.</strong> Player names, group names, colours and assignments are included.','good');}
  async function upload(e){const file=e.target.files?.[0];if(!file)return;try{const text=await file.text(),cfg=parseCompatible(text);if(!cfg)throw new Error('invalid');recordHistory();setupDraft=cfg;selectedPlayerId=null;setupDraft.groups.forEach((g,i)=>{const n=$(`#groupName-${i}`),c=$(`#groupColor-${i}`);if(n)n.value=g.name||`Group ${i+1}`;if(c)c.value=g.color;});recomputeValidation();setupDirty=setupSavedSignature!==signature(cfg);renderTags();const assigned=cfg.groups.reduce((n,g)=>n+g.memberIds.length,0),nameProblem=cfg.players.some(p=>[...p.name.trim()].length>12),gErrors=groupErrors(cfg);if(nameProblem||gErrors.length)toast(`<strong>Uploaded setup needs attention:</strong> ${nameProblem?'Player names must be 12 characters or fewer':gErrors.join(' · ')}`,'bad');else toast(`<strong>Game_Setup.txt loaded.</strong> ${cfg.players.length}/30 player names · ${assigned}/30 assigned a group.`,'good');refreshButtons();refreshHistory();}catch(err){toast('<strong>Upload failed:</strong> this is not a compatible Edu Play Lab Game Setup file.','bad');errorSound();}finally{e.target.value='';}}

  function open(options={}){
    ctx={app:options.app||document.getElementById('app'),overlayRoot:options.overlayRoot||document.getElementById('overlayRoot'),toolbarHTML:options.toolbarHTML||(()=>''),bindToolbar:options.bindToolbar||(()=>{}),onBack:options.onBack||(()=>{}),onApply:options.onApply||(()=>{}),gameStateKey:options.gameStateKey||'',errorSound:options.errorSound||(()=>{}),successSound:options.successSound||(()=>{})};
    if(ctx.overlayRoot)ctx.overlayRoot.innerHTML='';selectedPlayerId=null;setupCheckedOnce=false;setupDirty=false;setupUndoStack=[];setupRedoStack=[];clearPointer();setupConfig=load();setupDraft=normalize(setupConfig)||blank();recomputeValidation();setupSavedSignature=setupConfig?signature(setupConfig):null;
    ctx.app.innerHTML=`<main class="screen setup-screen"><div class="setup-topbar"><button class="icon-btn setup-back" id="setupBackBtn" title="Back">←</button><div class="setup-title-wrap"><h1>Game Setup</h1></div><div class="setup-history"><button class="icon-btn" id="undoSetupBtn" title="Undo" aria-label="Undo setup change" disabled>↶</button><button class="icon-btn" id="redoSetupBtn" title="Redo" aria-label="Redo setup change" disabled>↷</button></div><div>${ctx.toolbarHTML()}</div></div><section class="setup-grid"><div class="setup-panel player-bank"><div class="setup-panel-label"><span>Player Names</span><span class="setup-count" id="playerCount">${setupDraft.players.length}/30</span></div><textarea class="player-entry" id="playerNamesInput" spellcheck="false" rows="1" placeholder="Enter one name per line"></textarea><div class="player-tags" id="playerTags"></div></div>${setupDraft.groups.map((g,i)=>{const col=2+Math.floor(i/2),row=i%2+1;return `<div class="setup-panel group-card" id="groupCard-${i}" data-group-index="${i}" style="grid-column:${col};grid-row:${row}"><div class="group-header"><input class="group-name-input" id="groupName-${i}" maxlength="12" value="${esc(g.name||`Group ${i+1}`)}" placeholder="Group ${i+1}" aria-label="Group ${i+1} name"><input class="group-colour" id="groupColor-${i}" type="color" value="${g.color}" title="Choose group colour" aria-label="Choose group ${i+1} colour"></div><div class="group-drop" id="groupDrop-${i}" data-group-index="${i}"></div><div class="group-player-count" id="groupCount-${i}">${g.memberIds.length}/5 players</div></div>`}).join('')}</section><div class="setup-actions"><button class="setup-action" id="uploadBtn">Upload ↑</button><button class="setup-action" id="randomizeBtn" disabled>Randomize ↻</button><button class="setup-action primary" id="addToGameBtn">Add player names to game</button><button class="setup-action" id="downloadSetupBtn" disabled>Download ↓</button></div><div class="setup-toast" id="setupToast" role="status" aria-live="polite"></div><input type="file" id="setupFileInput" accept=".txt,.json,text/plain,application/json" class="hidden"></main>`;
    ctx.bindToolbar();$('#setupBackBtn').onclick=ctx.onBack;$('#undoSetupBtn').onclick=undo;$('#redoSetupBtn').onclick=redo;refreshHistory();bindNameEntry($('#playerNamesInput'),names=>addToBank(names));setupDraft.groups.forEach((g,i)=>{const name=$(`#groupName-${i}`);armTextHistory(name);name.addEventListener('input',()=>{if(setupDraft?.groups?.[i])setupDraft.groups[i].name=name.value.trim()||`Group ${i+1}`;markDirty();});name.addEventListener('blur',()=>{if(!name.value.trim()){name.value=`Group ${i+1}`;if(setupDraft?.groups?.[i])setupDraft.groups[i].name=name.value;markDirty();}});const colour=$(`#groupColor-${i}`);let captured=false;colour.addEventListener('pointerdown',()=>{if(!captured){recordHistory();captured=true;}});colour.addEventListener('focus',()=>captured=false);colour.addEventListener('keydown',()=>{if(!captured){recordHistory();captured=true;}});colour.addEventListener('change',()=>captured=false);colour.addEventListener('input',e=>{if(setupDraft?.groups?.[i])setupDraft.groups[i].color=e.target.value;document.querySelectorAll(`#groupDrop-${i} .player-tag`).forEach(tag=>tag.style.background=e.target.value);markDirty();});});$('#uploadBtn').onclick=()=>$('#setupFileInput').click();$('#setupFileInput').onchange=upload;$('#randomizeBtn').onclick=randomize;$('#addToGameBtn').onclick=addToGame;$('#downloadSetupBtn').onclick=download;renderTags();refreshButtons();
  }

  global.EduPlayGameSetup={STORAGE_KEY,GROUP_IDS,DEFAULT_GROUP_COLORS,normalize,isReady,toGroups,load,persist,serialize,parseCompatible,open};
})(window);
